import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
import { Toaster } from "react-hot-toast";

import { ModeToggle } from "@/components/Theme/Toggle";
import Header from "@/components/Header/Header";
import { ReCaptchaProvider } from "next-recaptcha-v3";
import Script from "next/script";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ReCaptchaProvider reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Script src="https://cdn.tailwindcss.com"/>
            <Header />
            {children}
            <Footer/>
            <Toaster />

          </ThemeProvider>
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
